#!/bin/bash

# Load the configuration file
source "/etc/motd-compiled"

# Fetch raspberry pi information
model=$(cat /sys/firmware/devicetree/base/model | tr -d '\0')
kernel=$(uname -sr)

# Print the header message
echo ""
echo " $(STYLE $INV_TITLE " $model ")$(STYLE $INV_SUBTITLE " $kernel ")"
