#!/bin/bash

# Load the configuration file
source "/etc/motd-compiled"

# Fetch up_count
up_count=$(bash -c "$UP_COUNT_CMD")

# Check if there are updates
if [ "$up_count" -gt 0 ]; then
    # Updates available
    color="$PRIMARY"
    inv_color="$INV_PRIMARY"

    # Singular or plural
    if [ "$up_count" -eq 1 ]; then
        s=""
    else
        s="s"
    fi
else
    # No updates
    color="$SUBTITLE"
    inv_color="$INV_SUBTITLE"
fi

# OUTPUT
echo " $(STYLE $color "$BULLET") $(STYLE $inv_color " $up_count ") $(STYLE $color "package$s can be upgraded")"
echo ""
